review:
  enabled: true
  auto_comment: true
  suggestions: true
  summary: false
  severity_levels: true
  rules:
    - readability
    - maintainability
    - performance
    - style
languages:
  - c
  - cpp
